select top 10 * from customer 

/*
Data has been successfully loaded into SQL Server.

The next step is to answer key business questions using SQL. These analyses
will help uncover customer purchasing behavior, sales trends, and other
valuable insights for business decision-making.
*/

/*
Q1. What is the total revenue generated by male vs female customers?
*/

select gender,sum(purchase_amount) as total_revenue
from customer
group by gender
order by total_revenue desc;

/*
Q2. Which customer used a discount but still spent more than the average purchase amount?
*/
select customer_id ,purchase_amount 
from customer
where discount_applied = 'Yes' 
AND 
purchase_amount > (select avg(purchase_amount) as average_amount from customer);


/*
Q3. Which are the top 5 products with highest average review ratings?
*/

select top 5
item_purchased,cast(avg(review_rating) as decimal(10,2)) as highest_avg_rating
from customer
group by item_purchased
order by highest_avg_rating desc

/*
Q4. Compare the average purchase amount between standard and express shipping?
*/

select 
shipping_type,AVG(purchase_amount) as avg_amount
from customer
where shipping_type in ('Express','Standard')
group by shipping_type
order by avg_amount desc

/*
Q5. Do subscribe customer spend more? compare avg spend and total revenue btw subscriber and non- subscriber?
*/

select subscription_status,
count(customer_id) as total_customers,
AVG(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by total_revenue desc

/*
Q6.Which 5 products have the highest percentage of purchases with discounts applied ?
*/

select top 5
     item_purchased,
     cast(100.0*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) as decimal(10,2)) as perc_of_purchases
from customer
group by item_purchased
order by perc_of_purchases desc

/*
Q7.segment customers into New,Returning and Loyal based on their total number of previous purchases and show the count of each segment?
*/

with segment_data as (
select customer_id,previous_purchases,
case 
   when previous_purchases = 1 then 'New Customer'
   when previous_purchases Between 2 and 10 then 'Returning Customer'
   else 'Loyal Customer' end 
as Customer_segment
from customer
)
select 
Customer_segment, count(*) as total_customers
from segment_data
group by Customer_segment

/*
Q8.What are the top 3 most purchased products within each category?
*/


with agg_data as (
select 
item_purchased,category,count(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id) desc) as rnk
from customer
group by item_purchased,category
)
select * from agg_data
where rnk <= 3;

/*
Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?
*/

select 
subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status
order by repeat_buyers desc

/*
10. What is the revenue contribution of each age group ?
*/

select 
age_group,SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc